[package]
name = "processr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
chumsky = "0.10.1"
clap = "4.5.40"
file-matcher = "0.7.0"
rand = "0.9.1"
regex = "1.11.1"
thiserror = "2.0.12"
